# Parametrize the transformations

#[generate]
#inputs =
#outputs =
#templates =

#[generate.mesh]
# No options for now

[generate.tasks]
waypoint_dist_to_corner = 0.7

[generate.gazebo]
ros_version = "ros1"
ros_pkg = "floorplan_models"

[generate.occ_grid]
map_laser_height = 0.7
map_border = 50
# map_server required metadata
map_resolution = 0.05
map_occupied_threshold = 0.65
map_free_threshold = 0.196
map_negate = 0
map_unknown_value = 200
map_occupied_value = 0
map_free_value = 255


#[generate.polyline]
# No options for now


[generate.door_keyframes]
keyframe_start = 0
keyframe_end = 180
keyframe_start_state = 0.0
keyframe_sampling_interval = 30
keyframe_state_change_probability = 0.5
