# Parametrize the transformations

#[generate]
#inputs =
#outputs =
#templates =

#[generate.mesh]
# No options for now

[generate.tasks]
dist_to_corner = 0.7

[generate.gazebo]
ros_version = "ros1"
ros_pkg = "floorplan_models"

[generate.occ_grid]
border = 50
# generation metadata
laser_height = 0.7
# map_server required metadata
resolution = 0.05
occupied_threshold = 0.65
free_threshold = 0.196
negate = 0
unknown_value = 200
occupied_value = 0
free_value = 255


#[generate.polyline]
# No options for now


[generate.door_keyframes]
start_frame = 0
end_frame = 180
start_state = 0.0
sampling_interval = 30
state_change_probability = 0.5
